name: $(BuildID)

trigger:
  - none

pool:
  vmImage: "windows-latest"

resources:
  repositories:
    - repository: CodeDeployment
      name: Accelerators/DeploymentEngine
      type: git
      ref: features/DeployDB

    - repository: PoCs
      name: PoCs/PoCs
      type: git
      ref: features/DeployToAzureSql

variables:
  - template: /Consumer-project/Variables/variables.yaml@self

extends:
  template: /Pipelines/Templates/common-code-deploy.yaml@CodeDeployment
  parameters:
    repositoryName: ${{ variables.repositoryName }}
    deploymentEnvironments: ${{variables.deploymentEnvironments}}
    deployments:
      - zipFileName: ${{ variables.zipFileName }}
        productName: ${{ variables.productName }}
        project: ${{ variables.project }}
        buildConfiguration: ${{ variables.buildConfiguration }}
    azureSubscriptions:
      - azureSubscription_DEV: ${{ variables.azureSubscription_DEV }}
        azureSubscription_TST: ${{ variables.azureSubscription_TST }}
        azureSubscription_SIT: ${{ variables.azureSubscription_SIT }}
        azureSubscription_UR:  ${{ variables.azureSubscription_UR }}
        azureSubscription_UAT: ${{ variables.azureSubscription_UAT }}
        azureSubscription_PRE: ${{ variables.azureSubscription_PRE }}
        azureSubscription_PRD: ${{ variables.azureSubscription_PRD }}
    resourceGroups:
      - resourceGroup_DEV: ${{ variables.resourceGroup_DEV }}
        resourceGroup_TST: ${{ variables.resourceGroup_TST }}
        resourceGroup_SIT: ${{ variables.resourceGroup_SIT }}
        resourceGroup_UR: ${{ variables.resourceGroup_UR }}
        resourceGroup_UAT: ${{ variables.resourceGroup_UAT }}
        resourceGroup_PRE: ${{ variables.resourceGroup_PRE }}
        resourceGroup_PRD: ${{ variables.resourceGroup_PRD }}
    serviceToDeploy: ${{ variables.serviceToDeploy }}
    serviceNames:
      - WebAppName: ${{ variables.WebAppName }}
        functionAppName: ${{ variables.functionAppName }}
        databaseName: ${{ variables.databaseName }}
    ServerName: ${{ variables.ServerName }}
    SqlUsername: ${{ variables.SqlUsername }}
    SqlPassword: ${{ variables.SqlPassword }}
    sqlFile: ${{ variables.sqlFile }}